GET localhost:3000

###

GET localhost:3000/api/ users?role='ADMIN'

###

GET localhost:3000/users/10

###

GET localhost:3000/users?role=ADMIN

###

POST localhost:3000/users
Content-Type: application/json

{
  "name": "mehrdad",
  "email": "mehrdad.kian71@gmail.com",
  "role": "ADMIN"
}

###

PATCH localhost:3000/users/6
Content-Type: application/json

{
  "email": "mehrdad"
}

###

DELETE localhost:3000/users/6

###########################################################################

GET localhost:3000/api/employees

###

GET localhost:3000/api/employees/2

###

GET localhost:3000/api/employees?role=ADMIN

###

POST localhost:3000/api/employees
Content-Type: application/json

{
  "name": "fear",
  "email": "fear@gmail.com",
  "role": "INTERN"
}

###

PATCH localhost:3000/api/employees/2
Content-Type: application/json

{
  "email": "lesco "
}

###

DELETE localhost:3000/api/employees/2